#!/bin/bash
set -ue


version=$( cat /etc/fedora-release )
regex='([0-9]+)'

if [[ $version =~ $regex ]]; then
    version="${BASH_REMATCH[1]}"
else
    echo "Your not running fedora or some shit" >&2
    exit 1
fi

sudo dnf install -y "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$version.noarch.rpm" 
sudo dnf install -y "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$version.noarch.rpm"

sudo dnf update -y

sudo dnf install -y xorg-x11-drv-nvidia akmod-nvidia
sudo dnf install -y xorg-x11-drv-nvidia-cuda #optional for cuda/nvdec/nvenc support
sudo dnf update -y

